# Generated by Django 5.0.4 on 2024-07-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueryPerformanceLog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylogperformance',
            old_name='DatebaseID',
            new_name='DatabaseID',
        ),
    ]
