# Generated by Django 5.0.4 on 2024-07-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueryPerformanceLog', '0002_rename_datebaseid_querylogperformance_databaseid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryLogPerformance',
            new_name='QueryPerformanceLog',
        ),
    ]
